[openai]
api_key = "sk-iM6Jc42voEnIOPSKJfFY0ri7chsz4D13sozKyqg403Euwv5e"
base_url = "https://api.chatanywhere.tech/v1"
[neo4j]
local_uri = "bolt://localhost:7687"
local_username = "test"
local_password = "Mikeno01"